# Generated by Django 4.1.5 on 2023-01-20 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='event_team',
        ),
        migrations.DeleteModel(
            name='EventTeam',
        ),
    ]
