# Generated by Django 4.1.5 on 2023-01-20 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_remove_service_event_team_delete_eventteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcatagory',
            name='catagory',
        ),
        migrations.AddField(
            model_name='service',
            name='account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='event_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
