# Generated by Django 4.1.5 on 2023-01-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_service_is_featured_remove_service_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='account',
            new_name='event_team',
        ),
    ]
