# Generated by Django 4.1.5 on 2023-01-20 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_account_service_event_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='event_team',
            new_name='account',
        ),
    ]
